<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

/**
 * Fires at start of header.php, immediately before `genesis_title` action hook to render the Doctype content.
 *
 * @since 1.3.0
 */
do_action( 'genesis_doctype' );

/**
 * Fires immediately after `genesis_doctype` action hook, in header.php to render the document title.
 *
 * @since 1.0.0
 */
do_action( 'genesis_title' );

/**
 * Fires immediately after `genesis_title` action hook, in header.php to render the meta elements.
 *
 * @since 1.0.0
 */
do_action( 'genesis_meta' );

wp_head(); // We need this for plugins.
?>
<link href="https://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400i,700,700i&amp;subset=latin-ext" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:100,100i,300,300i,400,400i,600,600i,700,700i&amp;subset=latin-ext" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo bloginfo('template_url'); ?>-sample/lib/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo bloginfo('template_url'); ?>-sample/lib/slick/slick-theme.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo bloginfo('template_url'); ?>-sample/style/style.css?ver=2" />
<link rel="stylesheet" type="text/css" href="<?php echo bloginfo('template_url'); ?>-sample/style/responsive.css?ver=2" />
</head>
<?php
genesis_markup(
	array(
		'open'    => '<body %s>',
		'context' => 'body',
	)
);
?>
<header>
	<a href="" class="logo"></a>
	<ul class="clearfix">
		<li><a href="#">HEALTH + WELLNESS</a></li>
		<li><a href="#">LIFE + STYLE</a></li>
		<li><a href="#">HOME + ENTERTAINING</a></li>
	</ul>
	<div class="navigation-control clearfix">
		<div class="search-btn"></div>
		<div class="menu-btn"></div>
	</div>
</header>

<div class="navigation-menu">
	<div class="nav-inner">
		<div class="close-button"></div>
		<div class="title">Categories</div>
		<ul class="clearfix">
			<li><a href="#">HEALTH + WELLNESS</a></li>
			<li><a href="#">LIFE + STYLE</a></li>
			<li><a href="#">HOME + ENTERTAINING</a></li>
		</ul>
		<div class="title">Links</div>
		<ul class="footer-list-left">
			<li><a href="#">About Us</a></li>
			<li><a href="#">Health Topics</a></li>
			<li><a href="#">Health News</a></li>
			<li><a href="#">FDA</a></li>
			<li><a href="#">Contact Us</a></li>
			<li><a href="#">Advertise With Us</a></li>
		</ul>
	</div>
</div>